[package]
name = "gabriel-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
gabriel-collection = { version = "0.1.0", path = "../gabriel-collection" }
gabriel-core = { version = "0.1.0", path = "../gabriel-core" }
gabriel-engine = { version = "0.1.0", path = "../gabriel-engine" }
gabriel-proxy = { version = "0.1.0", path = "../gabriel-proxy" }
gabriel-vault = { version = "0.1.0", path = "../gabriel-vault" }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "signal"] }
toml = "1.1.4"

[[bin]]
name = "gabriel"
path = "src/main.rs"
